CREATE TABLE IF NOT EXISTS links (
  id bigint generated by default as identity primary key,
  code text not null unique,
  original_url text not null,
  source text not null check (source in ('web', 'telegram')),
  clicks int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_links_code ON links (code);
